name: Integrate Infrastructure
on:
  pull_request:
    paths:
      - .github/workflows/integrate-infrastructure.yaml
      - "infra/terraform/**"
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-code-format:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.14.0"
      - name: Check code format
        run: terraform fmt -check -recursive ./infra/terraform
  validation:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.14.0"
      - name: Initialize Terraform working directory
        run: terraform -chdir=./infra/terraform init -backend=false
      - name: Validate configuration files
        run: terraform -chdir=./infra/terraform validate
  plan:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::941594947146:role/harmattan-stg-github-actions
          aws-region: ap-northeast-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.14.0"
      - name: Initialize terraform working directory
        run: terraform -chdir=./infra/terraform init -backend-config=stg.tfbackend -reconfigure
      - id: plan
        name: Generates a execution plan
        run: terraform -chdir=./infra/terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_env: stg
      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            const stdout = `${{ steps.plan.outputs.stdout }}`;
            const stderr = `${{ steps.plan.outputs.stderr }}`;

            let output = `Terraform Plan: \`${{ steps.plan.outcome }}\`

            <details><summary>Show plan</summary>

            \`\`\`
            ${stdout}
            \`\`\`
            </details>`;

            if (stderr) {
              output += `
            <details><summary>Show errors</summary>

            \`\`\`
            ${stderr}
            \`\`\`
            </details>
            `;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
