name: Integrate Infrastructure
on:
  pull_request:
    paths:
      - .github/workflows/integrate-infrastructure.yaml
      - "infra/terraform/**"
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-code-format:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.14.0"
      - name: Check code format
        run: terraform fmt -check -recursive ./infra/terraform
  validation:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.14.0"
      - name: Initialize Terraform working directory
        run: terraform -chdir=./infra/terraform init -backend=false
      - name: Validate configuration files
        run: terraform -chdir=./infra/terraform validate
  plan:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - name: Build Lambda functions
        run: GOOS=linux GOARCH=arm64 go build -o ./infra/lambdas/hello/bootstrap -buildvcs=false ./infra/lambdas/hello
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::941594947146:role/harmattan-stg-github-actions
          aws-region: ap-northeast-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.14.0"
      - name: Initialize terraform working directory
        run: terraform -chdir=./infra/terraform init -backend-config=stg.tfbackend -reconfigure
      - id: plan
        name: Generates a execution plan
        run: terraform -chdir=./infra/terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_env: stg
      - name: Create comment
        uses: actions/github-script@v8
        with:
          script: |
            const stdout = `${{ steps.plan.outputs.stdout }}`;
            const stderr = `${{ steps.plan.outputs.stderr }}`;

            let output = `Terraform Plan: \`${{ steps.plan.outcome }}\`

            <details><summary>Show plan</summary>

            \`\`\`
            ${stdout}
            \`\`\`
            </details>`;

            if (stderr) {
              output += `
            <details><summary>Show errors</summary>

            \`\`\`
            ${stderr}
            \`\`\`
            </details>
            `;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Fail if plan failed
        if: steps.plan.outcome == 'failure'
        run: exit 1
